// <auto-generated />
namespace CakesMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Edited_Photo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edited_Photo));
        
        string IMigrationMetadata.Id
        {
            get { return "201505032057184_Edited_Photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
